module.exports = {
  plugins: [
    'tailwindcss',
    process.env.NODE_ENV === 'production'
      ? [
          '@fullhuman/postcss-purgecss',
          {
            content: ['./pages/**/*.{js,jsx,ts,tsx}', './src/components/**/*.{js,jsx,ts,tsx}'],
            defaultExtractor: content => content.match(/[\w-/:]+(?<!:)/g) || [],
            whitelist: [
              'html',
              'body',
              'w-1/12',
              'w-2/12',
              'w-3/12',
              'w-4/12',
              'w-5/12',
              'w-6/12',
              'w-7/12',
              'w-8/12',
              'w-9/12',
              'w-10/12',
              'w-11/12',
              'w-12/12',
              'sm:w-1/12',
              'sm:w-2/12',
              'sm:w-3/12',
              'sm:w-4/12',
              'sm:w-5/12',
              'sm:w-6/12',
              'sm:w-7/12',
              'sm:w-8/12',
              'sm:w-9/12',
              'sm:w-10/12',
              'sm:w-11/12',
              'sm:w-12/12',
              'md:w-1/12',
              'md:w-2/12',
              'md:w-3/12',
              'md:w-4/12',
              'md:w-5/12',
              'md:w-6/12',
              'md:w-7/12',
              'md:w-8/12',
              'md:w-9/12',
              'md:w-10/12',
              'md:w-11/12',
              'md:w-12/12',
              'lg:w-1/12',
              'lg:w-2/12',
              'lg:w-3/12',
              'lg:w-4/12',
              'lg:w-5/12',
              'lg:w-6/12',
              'lg:w-7/12',
              'lg:w-8/12',
              'lg:w-9/12',
              'lg:w-10/12',
              'lg:w-11/12',
              'lg:w-12/12',
            ],
          },
        ]
      : undefined,
    'autoprefixer',
    'postcss-preset-env',
  ],
};
